<?php

return [
    'connection' => env('LEGACY_DB_CONNECTION', 'legacy_mysql'),

    'epic_house_epic_code' => env('LEGACY_V1_HOUSE_EPIC_CODE', 'EPIC-HOUSE'),

    'sources' => [
        'users' => [
            'table' => env('LEGACY_V1_USERS_TABLE', 'users'),
            'columns' => [
                'legacy_user_id' => env('LEGACY_V1_USERS_COL_ID', 'id'),
                'name' => env('LEGACY_V1_USERS_COL_NAME', 'name'),
                'epic_id' => env('LEGACY_V1_USERS_COL_EPIC_ID', 'epic_id'),
                'email' => env('LEGACY_V1_USERS_COL_EMAIL', 'email'),
                'whatsapp' => env('LEGACY_V1_USERS_COL_WHATSAPP', 'whatsapp'),
                'sponsor_epic_id' => env('LEGACY_V1_USERS_COL_SPONSOR_EPIC_ID', 'sponsor_epic_id'),
                'city' => env('LEGACY_V1_USERS_COL_CITY', 'city'),
                'password_hash' => env('LEGACY_V1_USERS_COL_PASSWORD_HASH', 'password'),
            ],
        ],
        'product_accesses' => [
            'table' => env('LEGACY_V1_PRODUCT_ACCESSES_TABLE', 'user_products'),
            'columns' => [
                'legacy_access_id' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_ID', 'id'),
                'legacy_user_id' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_USER_ID', 'user_id'),
                'epic_id' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_EPIC_ID', 'epic_id'),
                'email' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_EMAIL', 'email'),
                'whatsapp' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_WHATSAPP', 'whatsapp'),
                'legacy_product_key' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_PRODUCT_KEY', 'product_code'),
                'legacy_product_name' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_PRODUCT_NAME', 'product_name'),
                'granted_at' => env('LEGACY_V1_PRODUCT_ACCESSES_COL_GRANTED_AT', 'granted_at'),
            ],
        ],
        'orders' => [
            'table' => env('LEGACY_V1_ORDERS_TABLE', 'orders'),
            'columns' => [
                'legacy_order_id' => env('LEGACY_V1_ORDERS_COL_ID', 'id'),
                'legacy_order_number' => env('LEGACY_V1_ORDERS_COL_NUMBER', 'order_number'),
                'legacy_user_id' => env('LEGACY_V1_ORDERS_COL_USER_ID', 'user_id'),
                'epic_id' => env('LEGACY_V1_ORDERS_COL_EPIC_ID', 'epic_id'),
                'customer_name' => env('LEGACY_V1_ORDERS_COL_CUSTOMER_NAME', 'customer_name'),
                'customer_email' => env('LEGACY_V1_ORDERS_COL_CUSTOMER_EMAIL', 'customer_email'),
                'customer_whatsapp' => env('LEGACY_V1_ORDERS_COL_CUSTOMER_WHATSAPP', 'customer_phone'),
                'status' => env('LEGACY_V1_ORDERS_COL_STATUS', 'status'),
                'currency' => env('LEGACY_V1_ORDERS_COL_CURRENCY', 'currency'),
                'subtotal_amount' => env('LEGACY_V1_ORDERS_COL_SUBTOTAL', 'subtotal_amount'),
                'discount_amount' => env('LEGACY_V1_ORDERS_COL_DISCOUNT', 'discount_amount'),
                'total_amount' => env('LEGACY_V1_ORDERS_COL_TOTAL', 'total_amount'),
                'ordered_at' => env('LEGACY_V1_ORDERS_COL_ORDERED_AT', 'created_at'),
                'paid_at' => env('LEGACY_V1_ORDERS_COL_PAID_AT', 'paid_at'),
            ],
        ],
        'payments' => [
            'table' => env('LEGACY_V1_PAYMENTS_TABLE', 'payments'),
            'columns' => [
                'legacy_payment_id' => env('LEGACY_V1_PAYMENTS_COL_ID', 'id'),
                'legacy_order_id' => env('LEGACY_V1_PAYMENTS_COL_ORDER_ID', 'order_id'),
                'legacy_payment_number' => env('LEGACY_V1_PAYMENTS_COL_NUMBER', 'payment_number'),
                'legacy_user_id' => env('LEGACY_V1_PAYMENTS_COL_USER_ID', 'user_id'),
                'epic_id' => env('LEGACY_V1_PAYMENTS_COL_EPIC_ID', 'epic_id'),
                'email' => env('LEGACY_V1_PAYMENTS_COL_EMAIL', 'email'),
                'status' => env('LEGACY_V1_PAYMENTS_COL_STATUS', 'status'),
                'payment_method' => env('LEGACY_V1_PAYMENTS_COL_METHOD', 'payment_method'),
                'provider' => env('LEGACY_V1_PAYMENTS_COL_PROVIDER', 'provider'),
                'provider_reference' => env('LEGACY_V1_PAYMENTS_COL_PROVIDER_REFERENCE', 'provider_reference'),
                'amount' => env('LEGACY_V1_PAYMENTS_COL_AMOUNT', 'amount'),
                'currency' => env('LEGACY_V1_PAYMENTS_COL_CURRENCY', 'currency'),
                'paid_at' => env('LEGACY_V1_PAYMENTS_COL_PAID_AT', 'paid_at'),
                'expired_at' => env('LEGACY_V1_PAYMENTS_COL_EXPIRED_AT', 'expired_at'),
            ],
        ],
        'commissions' => [
            'table' => env('LEGACY_V1_COMMISSIONS_TABLE', 'commissions'),
            'columns' => [
                'legacy_commission_id' => env('LEGACY_V1_COMMISSIONS_COL_ID', 'id'),
                'user_epic_id' => env('LEGACY_V1_COMMISSIONS_COL_USER_EPIC_ID', 'user_epic_id'),
                'user_name' => env('LEGACY_V1_COMMISSIONS_COL_USER_NAME', 'user_name'),
                'user_email' => env('LEGACY_V1_COMMISSIONS_COL_USER_EMAIL', 'user_email'),
                'user_whatsapp' => env('LEGACY_V1_COMMISSIONS_COL_USER_WHATSAPP', 'user_whatsapp'),
                'sponsor_epic_id' => env('LEGACY_V1_COMMISSIONS_COL_SPONSOR_EPIC_ID', 'sponsor_epic_id'),
                'downline_epic_id' => env('LEGACY_V1_COMMISSIONS_COL_DOWNLINE_EPIC_ID', 'downline_epic_id'),
                'downline_name' => env('LEGACY_V1_COMMISSIONS_COL_DOWNLINE_NAME', 'downline_name'),
                'product_code' => env('LEGACY_V1_COMMISSIONS_COL_PRODUCT_CODE', 'product_code'),
                'product_name' => env('LEGACY_V1_COMMISSIONS_COL_PRODUCT_NAME', 'product_name'),
                'commission_type' => env('LEGACY_V1_COMMISSIONS_COL_TYPE', 'commission_type'),
                'commission_level' => env('LEGACY_V1_COMMISSIONS_COL_LEVEL', 'commission_level'),
                'commission_amount' => env('LEGACY_V1_COMMISSIONS_COL_AMOUNT', 'commission_amount'),
                'commission_status' => env('LEGACY_V1_COMMISSIONS_COL_STATUS', 'commission_status'),
                'earned_at' => env('LEGACY_V1_COMMISSIONS_COL_EARNED_AT', 'earned_at'),
                'approved_at' => env('LEGACY_V1_COMMISSIONS_COL_APPROVED_AT', 'approved_at'),
                'paid_at' => env('LEGACY_V1_COMMISSIONS_COL_PAID_AT', 'paid_at'),
                'period_month' => env('LEGACY_V1_COMMISSIONS_COL_PERIOD_MONTH', 'period_month'),
                'period_year' => env('LEGACY_V1_COMMISSIONS_COL_PERIOD_YEAR', 'period_year'),
                'legacy_order_id' => env('LEGACY_V1_COMMISSIONS_COL_ORDER_ID', 'legacy_order_id'),
                'note' => env('LEGACY_V1_COMMISSIONS_COL_NOTE', 'note'),
            ],
        ],
        'payouts' => [
            'table' => env('LEGACY_V1_PAYOUTS_TABLE', 'payouts'),
            'columns' => [
                'legacy_payout_id' => env('LEGACY_V1_PAYOUTS_COL_ID', 'id'),
                'legacy_user_id' => env('LEGACY_V1_PAYOUTS_COL_USER_ID', 'user_id'),
                'user_epic_id' => env('LEGACY_V1_PAYOUTS_COL_USER_EPIC_ID', 'user_epic_id'),
                'user_email' => env('LEGACY_V1_PAYOUTS_COL_USER_EMAIL', 'user_email'),
                'status' => env('LEGACY_V1_PAYOUTS_COL_STATUS', 'status'),
                'amount' => env('LEGACY_V1_PAYOUTS_COL_AMOUNT', 'amount'),
                'requested_at' => env('LEGACY_V1_PAYOUTS_COL_REQUESTED_AT', 'requested_at'),
                'approved_at' => env('LEGACY_V1_PAYOUTS_COL_APPROVED_AT', 'approved_at'),
                'paid_at' => env('LEGACY_V1_PAYOUTS_COL_PAID_AT', 'paid_at'),
                'note' => env('LEGACY_V1_PAYOUTS_COL_NOTE', 'note'),
            ],
        ],
    ],
];
